Let-s-Jam/letsjamFE

src/app/jammer-profile/jammer-profile.component.css, src/app/jammer-profile/jammer-profile.component.html
=> add more styling

src/app/accepted-jammers/accepted-jammers.component.html, src/app/accepted-jammers/accepted-jammers.component.spec.ts, src/app/accepted-jammers/accepted-jammers.component.ts, src/app/app.module.ts, src/app/jam-requests/jam-requests.component.html, src/app/jam-requests/jam-requests.component.spec.ts, src/app/jam-requests/jam-requests.component.ts, src/app/user-profile/user-profile.component.html, src/app/user-profile/user-profile.component.spec.ts, src/app/user-profile/user-profile.component.ts
Description
We added user profile components and jam request components and basic architecture.
Type of change
Checklist:
=> Add user profile components and jam request components and basic architecture

src/app/header/header.component.html
Description
Added a home button
Type of change
Checklist:
=> Add home button

src/app/jammer-profile/jammer-profile.component.html, src/app/jammer-profile/jammer-profile.component.ts, src/dummy-data.ts
Description
We added user profile components and jam request components and basic architecture.
Type of change
Checklist:
=> Add dummy test file and imports for local testing before using dummy server

src/app/jammer-profile/jammer-profile.component.html, src/app/jammer-profile/jammer-profile.component.ts
Description
Dynamically render other user data to search results page
Type of change
Checklist:
=> Dynamically render other user data to search results page

src/app/app.module.ts, src/app/jammer-profile/jammer-profile.component.ts, src/app/services/user-service.ts
Description
Add user service and injectable for retrieving search data from mock API
Type of change
Checklist:
=> Add user service and injectable for retrieving search data from mock API

src/app/services/user-service.ts
Fix JSON shape, remove type text from getJammers method to complete functionality
Type of change
Checklist:
=> Fix JSON shape, remove type text from getJammers method to complete functionality

src/app/services/user-service.ts, src/app/user-profile/user-profile.component.ts
Description
Add getUserProfile method to userService, add subscription to ngOnInit in user profile component
Type of change
Checklist:
=> Add getUserProfile method to userService, add subscription to ngOnInit in user profile component

src/app/jammer-profile/jammer-profile.component.ts, src/app/services/user-service.ts, src/app/user-profile/user-profile.component.html, src/app/user-profile/user-profile.component.ts
Description
Add UserService provider to user profile component, make user profile dynamically display user data
Type of change
Checklist:
=> Add UserService provider to user profile component, make user profile dynamically display user data

src/app/jam-requests/jam-requests.component.html, src/app/jam-requests/jam-requests.component.ts, src/app/jammer-profile/jammer-profile.component.html, src/app/jammer-profile/jammer-profile.component.ts, src/app/services/user-service.ts, src/app/user-profile/user-profile.component.ts
Description
Refactor paths, add dynamic user info and pictures to incoming requests section
Type of change
Checklist:
=> Refactor paths, add dynamic user info and pictures to incoming requests section

src/app/accepted-jammers/accepted-jammers.component.css, src/app/header/header.component.css, src/app/jam-requests/jam-requests.component.css, src/app/jammer-profile/jammer-profile.component.css, src/app/jammer-profile/jammer-profile.component.html, src/app/user-profile/user-profile.component.css
Add more styling to the page, add scroll bar, add flex box several components
=> Add more styling to the page, add scroll bar, add flex box several components

src/app/accepted-jammers/accepted-jammers.component.html, src/app/accepted-jammers/accepted-jammers.component.ts, src/app/services/user-service.ts
Description
Add subscription for friends list, make friends list display dynamic data, add genres category
Type of change
Checklist:
=> Add subscription for friends list, make friends list display dynamic data, add genres category

src/app/jam-requests/jam-requests.component.css, src/app/jam-requests/jam-requests.component.html, src/app/user-edit/user-edit.component.css, src/app/user-info/user-info.component.css, src/app/user-profile/user-profile.component.css, src/app/user-profile/user-profile.component.html
Description
Added further styling to user-profile page
Pending Jam Requests appear on the right side of the logged-in user's information, resized to be smaller
Added border around user info/edit components as well as pending requests
Flexed items into place with additional divs 
Standardized font choices
Type of change
[x] Styling
Checklist:
[] My changes generate no new warnings
=> Added divs and flexbox to rearrange user-profile page

src/app/jam-requests/jam-requests.component.css, src/app/user-profile/user-profile.component.css
Add styling to the page to make it more accessible on different screens
=> Add styling to the page to make it more accessible on different screens

src/app/accepted-jammers/accepted-jammers.component.ts, src/app/jam-requests/jam-requests.component.ts, src/app/jammer-profile/jammer-profile.component.ts, src/app/services/user-service.ts
-Updated endpoints for getting user's connections
Fixes # (issue)
Please delete options that are not relevant.
=> Update endpoints for getting friends and pending friends

src/app/accepted-jammers/accepted-jammers.component.spec.ts
Start implementing Jasmine in testing spec of accepted-jammers
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. 
- [ x] Jasmine
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [ x] I have made corresponding changes to the documentation (as needed)
=> Start implementing Jasmine in testing spec of accepted-jammers

src/app/services/user-service.ts, src/app/user-edit/user-edit.component.html, src/app/user-edit/user-edit.component.ts
Description
Updated fetch request to include body and options definitions
Checklist:
[x ] My code follows the style guidelines of this project
I have commented my code, particularly in hard-to-understand areas
My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes
=> Give PATCH request defined body and options, update function

src/app/jammer-profile/jammer-profile.component.ts, src/app/services/user-service.ts, src/app/user-info/user-info.component.html, src/app/user-info/user-info.component.ts
Refactor the user info html to display the user's instrument and genre
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
=> Refactor the user info html to display the user's instrument and genre

package-lock.json, package.json, src/app/jammer-profile/jammer-profile.component.css, src/app/jammer-profile/jammer-profile.component.ts, src/app/results-page/results-page.component.html, src/app/results-page/results-page.component.ts, src/app/searchbar/searchbar.component.html, src/app/searchbar/searchbar.component.ts, src/app/user-profile/user-profile.component.css, src/styles.css
Description
Add emitter for the search form, refactor other components to accommodate
Type of change
Checklist:
=> Add emitter for the search form, refactor other components to accommodate

src/app/searchbar/searchbar.component.html, src/app/searchbar/searchbar.component.ts
Description
Add logic to handle adding search terms to URI
Type of change
Checklist:
=> Add logic to handle adding search terms to URI

src/app/jammer-profile/jammer-profile.component.ts, src/app/results-page/results-page.component.html, src/app/results-page/results-page.component.ts, src/app/searchbar/searchbar.component.ts, src/app/services/user-service.ts
Description
Add styling for background and containers, refactor naming conventions to bring frontend in line with backend
Type of change
Checklist:
=> Add observable for sendJammerSearchParams

src/app/jammer-profile/jammer-profile.component.html, src/app/jammer-profile/jammer-profile.component.ts, src/app/searchbar/searchbar.component.ts, src/app/services/user-service.ts
Description
Fix userService, add loops to iterate over data structure, refactor services
Type of change
Checklist:
=> Fix userService, add loops to iterate over data structure, refactor services

src/app/accepted-jammers/accepted-jammers.component.html, src/app/jam-requests/jam-requests.component.html, src/app/jammer-profile/jammer-profile.component.html, src/app/jammer-profile/jammer-profile.component.ts, src/app/searchbar/searchbar.component.html, src/app/services/user-service.ts
Change zipcode and distance in the components bringing in that data, Adjusted the data in jammer-profile component to re
cieve the data properly
Displays the users in the search for jammers view
Please delete options that are not relevant.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Change zipcode and distance in the components bringing in that data

src/app/jam-requests/jam-requests.component.html, src/app/jam-requests/jam-requests.component.ts, src/app/services/user-service.ts
Description
-Created a patch request that interpolates the id of the jammer into a uri to send to the backend
-Added a function to be called withiin the jam-request component upon button click of the "Let's Jam" button
Type of change
Checklist:
=> Add patch to accept jam requests, add function to call patch on click

src/app/jam-requests/jam-requests.component.ts
Description
-Github did not show us the full extent of the merge conflict, incredible stuff
Type of change
Checklist:
=> Github did not show us the full extent of the merge conflict, incredible stuff

src/app/services/user-service.ts
Description
-All HTTP requests are HTTPS so that it runs on deployment
Type of change
Checklist:
=> Make http requests into https requests

src/app/accepted-jammers/accepted-jammers.component.html, src/app/accepted-jammers/accepted-jammers.component.ts, src/app/app.module.ts, src/app/jam-requests/jam-requests.component.ts, src/app/jammer-profile/jammer-profile.component.css, src/app/jammer-profile/jammer-profile.component.html, src/app/jammer-profile/jammer-profile.component.ts, src/app/results-page/results-page.component.html, src/app/results-page/results-page.component.ts, src/app/searchbar/searchbar.component.ts, src/app/services/user-service.ts, src/app/services/user-services.spec.ts, src/app/user-edit/user-edit.component.ts, src/app/user-info/user-info.component.ts, src/app/user-profile/user-profile.component.html, src/app/user-profile/user-profile.component.ts
Description
remove console logs and code comments, fix bug affecting users displaying to friends section
Fixes
fixed bug affecting users displaying to friends section
Type of change
refactoring, bugfix
[x] Bug fix (non-breaking change which fixes an issue)
Checklist:
=> remove console logs and code comments, fix bug affecting users displaying to friends section
